name: example

environment:
  # shared preferences 2021-03-25:
  sdk: ">=2.12.0-259.9.beta <3.0.0"
  flutter: ">=1.12.13+hotfix.5"
  #sdk: ">=2.7.0 <3.0.0"
  #flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  prefnotifiers: any
    #path: ../../prefnotifiers_flutter

