# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/i18n/**
    #- test/**
  language:
    strict-casts: true
    strict-raw-types: true
    strict-inference: true

  errors:
    await_only_futures: error
    depend_on_referenced_packages: error
    unawaited_futures: error
    unrelated_type_equality_checks: error
    tighten_type_of_initializing_formals: error
    parameter_assignments: error
    avoid_void_async: error
    invalid_use_of_protected_member: error
    invalid_use_of_visible_for_testing_member: error
    missing_enum_constant_in_switch: error

linter:
  rules:
    unnecessary_this: false
    constant_identifier_names: false
    avoid_print: false
    unawaited_futures: true
    unnecessary_await_in_return: true

    # параметры объявляются без слова local, но никогда не реассигнятся
    parameter_assignments: true
    avoid_final_parameters: true


    prefer_const_declarations: true
    prefer_final_locals: true
    prefer_final_fields: true
    #prefer_final_parameters: true
    prefer_final_in_for_each: true

    always_declare_return_types: true
    unrelated_type_equality_checks: true
    tighten_type_of_initializing_formals: true
    unnecessary_lambdas: true
    use_decorated_box: true
    use_colored_box: true
    prefer_if_elements_to_conditional_expressions: true
    sort_constructors_first: true
    use_named_constants: true
    use_super_parameters: true
    use_test_throws_matchers: true
    cascade_invocations: true
    avoid_unused_constructor_parameters: true
    avoid_void_async: true
    dangling_library_doc_comments: true