name: prefnotifiers
description: Represents shared preferences as ValueNotifier objects. Reads and writes occur asynchronously in background.
version: 1.0.9+0
homepage: https://github.com/rtmigo/prefnotifiers

environment:
  sdk: '>=2.15.0 <4.0.0'

dependency_overrides:
  collection:
  analyzer:

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

