name: test-and-merge

on:
  push:
    branches: [dev]
    paths-ignore:
      - 'example/*'
      - '**.md'
      - '**.txt'

  pull_request:
    branches: [dev]
    paths-ignore:
      - 'example/*'
      - '**.md'
      - '**.txt'

jobs:
  test:
    timeout-minutes: 9
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest] #, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          #flutter-version: '2.0.3'
          channel: 'stable'
      - name: Install dependencies
        run: |
          git config --global url."https://${{ secrets.PRIVATE_REPOS_TOKEN }}@github".insteadOf https://github
          flutter pub get
      - name: Run tests
        run: flutter test

  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          #flutter-version: '2.0.3'
          channel: 'stable'
      - name: Install dependencies
        run: |
          git config --global url."https://${{ secrets.PRIVATE_REPOS_TOKEN }}@github".insteadOf https://github
          flutter pub get
      - name: Analyze
        #run: flutter analyze --fatal-infos
        run: flutter analyze --no-fatal-infos
    timeout-minutes: 5
  #      - name: Publish (dry run)
  #        run: flutter pub publish --dry-run

  merge-to-staging:
    needs: [test, analyze]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Merge current -> staging
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          target_branch: staging
          github_token: ${{ github.token }}
    timeout-minutes: 5